name: Wietze-Gemeinschaft

lang: de_DE
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      
permalink: /:title